### ISSUE TITLE
bug dans le mode normal le perso tombe

### ISSUE THREAD

**Issue by AdrienJarretier** [guillaume-gomez/MathGame#4]

**Comment by guillaume-gomez** [comment]
plus détail please

**Comment by AdrienJarretier** [comment]
en lancant le jeu en mode normal le perso tombait direct, enfait la partie etait lancée dessuite alors meme qu'il n'y avait aucune courbe, si ca ne te le fait pas , c'etait probablement due au fait qu'il manquait une partie des niveaux.

**Comment by guillaume-gomez** [comment]
Ok a regarder en priorité alors
